name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  # ────────────────
  # 1. Build Job
  # ────────────────
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload docs folder
        if: matrix.node-version == '20.x' # Only one version uploads
        uses: actions/upload-artifact@v4
        with:
          name: docs-folder
          path: docs

  # ────────────────
  # 2. Deploy Job
  # ────────────────
  deploy:
    needs: build
    runs-on: ubuntu-latest

    # extra scopes only this job needs
    permissions:
      pages: write
      id-token: write

    # sets the Pages‑link pill in the UI
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy                   # expose page_url output
        uses: actions/deploy-pages@v4
